// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtBA8MkJwf6tPf6hoGHkoK7oh6javtFA',
    appId: '1:90320196189:web:2d6574165491f67c6033b4',
    messagingSenderId: '90320196189',
    projectId: 'mobileaichatbot',
    authDomain: 'mobileaichatbot.firebaseapp.com',
    storageBucket: 'mobileaichatbot.firebasestorage.app',
    measurementId: 'G-2FZZZHZ97P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZvL1aDVGgkw9ttc8Ut1XF49deJf6a8k',
    appId: '1:90320196189:android:79f88166ce2898c16033b4',
    messagingSenderId: '90320196189',
    projectId: 'mobileaichatbot',
    storageBucket: 'mobileaichatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_yfGYqf1hyjkcuQxWv1N_gPQmQr_uOU',
    appId: '1:90320196189:ios:7a2cf7a879db974d6033b4',
    messagingSenderId: '90320196189',
    projectId: 'mobileaichatbot',
    storageBucket: 'mobileaichatbot.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_yfGYqf1hyjkcuQxWv1N_gPQmQr_uOU',
    appId: '1:90320196189:ios:7a2cf7a879db974d6033b4',
    messagingSenderId: '90320196189',
    projectId: 'mobileaichatbot',
    storageBucket: 'mobileaichatbot.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJtBA8MkJwf6tPf6hoGHkoK7oh6javtFA',
    appId: '1:90320196189:web:6febb34a919efd136033b4',
    messagingSenderId: '90320196189',
    projectId: 'mobileaichatbot',
    authDomain: 'mobileaichatbot.firebaseapp.com',
    storageBucket: 'mobileaichatbot.firebasestorage.app',
    measurementId: 'G-6LN9EHTZRL',
  );

}